application:
  title: FPT International Student Exchange
  currency:
    vnd:
      format: "%n %u"
      unit: VNĐ
      precision: 0
model:
  user:
    max_name_length: 30
    min_name_length: 3
    year_interval: 40
    phone_number:
      minimum: 10
      maximum: 15
  event:
    sorted_by:
      latest: latest
      most_popular: most_popular
    per_page: 5
    max_title_length: 30
    date_format: "%d/%m/%y"
    zero: 0
    minimum_participant: 1
  user_enroll_event:
    status:
      unenroll: "unenroll"
  message:
    date_format: "%d/%m/%y"
    time_format: "%l:%M %p"
  transcript:
    pass_mark: 5
assets:
  images:
    fpt_logo: fpt_logo.png
date:
  formats:
    long: "%e, %B %Y"
regex:
  only_word: !ruby/regexp '/[a-zA-Z0-9\s]/'
  word_with_number: !ruby/regexp '/[a-zA-Z0-9]/'
  roll_number: !ruby/regexp '/[A-Z0-9]+/'
  upper_case: !ruby/regexp '/[A-Z]/'
